### ISSUE TITLE
【Proposal】Hey社様ロゴ切り替え

### ISSUE THREAD

**Issue by maito1201** [GoCon/2022spring#104]
refs: https://www.hey.jp/news/2022-08-31-hey-to-stores

Hey株式会社の会社名、ロゴの刷新に伴い、スポンサーロゴを切り替えるのはいかがでしょうか

![image](https://user-images.githubusercontent.com/49754654/187592859-666a4777-c526-48e5-8f52-fbc15c556fda.png)

**Comment by ymotongpoo** [comment]
ロゴはHey社のブランドですので、変更をするのであればHey社の確認が必要ですね

**Comment by maito1201** [comment]
特に変更する予定はない、とのご報告を頂きました
